// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "6495022e-8472-43b3-8a62-aa865861df89");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1579078558);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1579078678);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 7309);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1579078527);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{88f35d95-4f2d-44b0-90ba-d92993b173bb}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1579078629351");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1579080412351");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1579078545757");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1579082145757");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1579078532");
user_pref("browser.slowStartup.averageTime", 5103);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1579078530);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1579078539124");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "b32245e30ddd45ad821bd1f0307e4409");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"ae530546-5a5a-4b5a-aeb7-e10ec8b343b4\",\"fxmonitor@mozilla.org\":\"1cc3e2c6-dcae-41d8-a75c-be498c8aa87f\",\"screenshots@mozilla.org\":\"368c3a40-5eb5-4962-bdd7-d721f0226e27\",\"webcompat-reporter@mozilla.org\":\"7c16dc1e-3a9b-4e45-a423-5077867eec87\",\"webcompat@mozilla.org\":\"81937dcd-775b-4f2a-ad27-8941383d86f3\",\"default-theme@mozilla.org\":\"48d0b6be-e8c9-4e46-a156-637f0e3d5abe\",\"google@search.mozilla.org\":\"77e1fa02-3cca-48e9-9aed-1937a418e795\",\"amazondotcom@search.mozilla.org\":\"b11d478e-70c1-4331-bf77-44d8e63814b2\",\"bing@search.mozilla.org\":\"b9e14382-7f5b-41f1-bd24-7d325209c80e\",\"ddg@search.mozilla.org\":\"104dc6c1-dc2b-4882-8afb-b98a3da38daf\",\"ebay@search.mozilla.org\":\"3631fd4a-8a22-4a1c-b532-636194b41d4e\",\"twitter@search.mozilla.org\":\"7e5b0f36-c34a-46ae-b2bb-e183aa88eff0\",\"wikipedia@search.mozilla.org\":\"ce063d16-371f-4d08-a876-061f6659254b\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1579078622);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190718161435");
user_pref("media.gmp-manager.lastCheck", 1579078620);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "201c5378-19eb-4d15-984b-1e87fe64bbaa");
user_pref("security.sandbox.plugin.tempDirSuffix", "d0782656-ce61-4d1b-af60-4eb3b08f2f40");
user_pref("services.blocklist.pinning.checked", 1579078619);
user_pref("services.settings.clock_skew_seconds", -1);
user_pref("services.settings.last_etag", "\"1579046413455\"");
user_pref("services.settings.last_update_seconds", 1579078619);
user_pref("services.settings.main.cfr-fxa.last_check", 1579078619);
user_pref("services.settings.main.cfr.last_check", 1579078619);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1579078619);
user_pref("services.settings.main.hijack-blocklists.last_check", 1579078619);
user_pref("services.settings.main.language-dictionaries.last_check", 1579078619);
user_pref("services.settings.main.normandy-recipes.last_check", 1579078619);
user_pref("services.settings.main.sites-classification.last_check", 1579078619);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1579078619);
user_pref("services.settings.security.onecrl.checked", 1579078619);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1579078524);
user_pref("toolkit.telemetry.cachedClientID", "1ac30128-ea0f-4b2d-922f-8b0342165968");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
